apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7687
      targetPort: bolt
      name: bolt
    - port: 7474
      targetPort: http
      name: http
  selector:
    app: {{ .Release.Name }}-neo4j
