apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-reports
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.reports.storageClass }}
  storageClassName: {{ .Values.reports.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.reports.storage }}
