apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  tenant-id: {{ .Values.secrets.tenantId | b64enc }}
  client-id: {{ .Values.secrets.clientId | b64enc }}
  client-secret: {{ .Values.secrets.clientSecret | b64enc }}
  neo4j-password: {{ .Values.secrets.neo4jPassword | b64enc }}
  neo4j-auth: {{ printf "neo4j/%s" .Values.secrets.neo4jPassword | b64enc }}
