{{- if and .Values.webapp.enabled .Values.webapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webapp
  {{- with .Values.webapp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webapp.ingress.className }}
  ingressClassName: {{ .Values.webapp.ingress.className }}
  {{- end }}
  {{- if .Values.webapp.ingress.tls }}
  tls:
    {{- toYaml .Values.webapp.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.webapp.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-webapp
                port:
                  name: http
{{- end }}
